### ISSUE TITLE
Scheduled On/Off Fails on Virtual Module

### ISSUE THREAD

**Issue by bwern** [genielabs/HomeGenie#274]
I have a two-switch in-wall module. Homegenie correctly identified it and created .1 and .2 virtual modules. I'm able to open poll for status and control the virtual modules through the web interface and directly through the API. However, setting Scheduled On/Off does not impact the switchs; at the correct time, the notification appears that it is turning that module on or off, but the module itself does not switch. Schedule on/off appears to work for other modules (single switches.)

**Comment by TasioX** [comment]
Try the new 517 version.  I had some issues with the scheduler that were resolved in 517.

**Comment by bwern** [comment]
Updated this evening and unfortunately still see the behavior.

**Comment by TasioX** [comment]
Check for disabled schedules in the scheduler and re-enable them if you find any.

**Comment by bwern** [comment]
All the schedules are enabled; no special schedules defined there -- just the out of the box. My Scheduled On/Off that is failing is using a cron entry though -- and it does seem to fire as evidenced by the Notify that comes up on screen. I am wondering if the "." in the module number might cause the issue since scheduled on/off on the normal modules is working fine; that's the only difference I can see in modules that work vs don't.

**Comment by TasioX** [comment]
Hmmm.  Is this a Csharp script?  Sometimes I have had to recompile some of the Csharp scripts I have after an update.  Similar behavior also many parts of the script work (Like the trigger) and other parts do not work.

**Comment by bwern** [comment]
This is the out-of-the-box Scheduled On/Off script. I did recompile it, but no luck. Writing a separate program that calls the module (6.1 in this case) works fine.

**Comment by genemars** [comment]
This bug was affecting only Z-Wave multi-instance virtual modules. I'm sending the fix now.
