### ISSUE TITLE
latest update 1.3-stable 8 updater issues

### ISSUE THREAD

**Issue by tuicemen** [genielabs/HomeGenie#404]
### Expected behavior
after updating to latest update Update icon should not appear and updates for prior versions shouldn't be showing for updates

### Actual behavior
after updating (hopefully to stable 8)using the HG auto update  the about shows I'm still at stable 6

### Steps to reproduce the problem starting from a fresh install

  1. in maintenace check search for update 
  after available date appear click update
  3. after update check about for version this shows  stable 6
 4. download stable 8 and do a manual update

### Specifications

  - Version: 1.3-stable.6, or 7 or 8 ?
  - Operating System: raspi (Buster)
  - .Net/Mono runtime version: latest
  - Hardware configuration: pi zero w cm15a

#### Additional configuration notes

Some strange things are happening with the Updates depending on how you do the update update check & update  puts you at stable6 with no new updates available  a manual update to 8 puts you at stable 8 but still show updates available versions stable 6 and stable 8 not 7

**Comment by tuicemen** [comment]
Note: this is behavior also apparent on my Linux Raspbian Bullseye beta machine as well if on staable 8 and you click update it puts you back to stable 6 and you lose add from newer builds so it is not just a typo

**Comment by mralapete** [comment]
Sounds like you're having a meltdown. Where are you accessing you're server from.

**Comment by genemars** [comment]
`stable.6` was not meant to appear among releases at all.
I've deleted it, this should fix the issue.

**Comment by soxfan1966** [comment]
I just updated to version 1.3 stable 8.  However, HG is still showing there is an update available (1.3 stable 8 again) and the yellow download arrow on the Dashboard is there.  

If I run "Update Check" it shows the update info etc.  I tried installing again but same thing.

**Comment by tuicemen** [comment]
Yes it still shows version 8 available here too.
The machine that updated to stable 6 shows no update and A manual update to 8 fails as it says the file is older.

**Comment by soxfan1966** [comment]
I did a restore of my backup settings - and it is currently working on / hung up on lib/mig/Microsoft.Owin.xml - been running for awhile on that same file.

**Comment by mralapete** [comment]
Sounds like you may have corrupted your HG install. Did you take an SD image of install before attempting to update. If so just restore that image to your SD card and attempt an update again.

If the isn’t possible delete the contents of the /homegenie folder and sub folders. Just grab the tarball file, tar it into the /homegenie folder. That will give you a fresh HG install and you can restore your HG settings backup via the HG GUI.

If you’re not comfortable working in the cli you could just do a fresh install via the HG deb package installer and restore your HG settings via the HG GUI.

**Comment by soxfan1966** [comment]
I would disagree with you there mralapete - I think there is something amiss with the update process having to do with the stable 6 and stable 8 issue.

**Comment by soxfan1966** [comment]
I am actually trying this process now (via Putty connected to my pi) as described here:
https://genielabs.github.io/HomeGenie/#/get_started

* I updated the below from stable 7 to stable 8.

wget https://github.com/genielabs/HomeGenie/releases/download/v1.3-stable.8/homegenie_1.3-stable.8_all.deb
sudo apt-get update
sudo apt-get install gdebi-core
sudo gdebi homegenie_1.3-stable.8_all.deb

Hoping once that finishes I can do a factory reset and then restore my saved configuration file.

**Comment by soxfan1966** [comment]
The process is still running in Putty.  It sent thru a bunch of things and then displayed a message about starting the homegenie .service - and its just been displaying a . on a new line over and over now.  I'm not sure if its still running the update or what but I am going to let it run.

**Comment by genemars** [comment]
Those dots is the installation process waiting for hg service to start. But it should start in less than 10 seconds. So it looks like something is wrong with the new installation script.

**Comment by soxfan1966** [comment]
OK - I am going to re-install stable 7 (I downloaded the tgz and am using the Manual Update routine now.

**Comment by genemars** [comment]
I just tested `stable.8` on a fresh new install of latest Raspbian Buster and it worked (only 2 dots were shown).
Did you try installing over and old homegenie box? If so, try removing the folder `/usr/local/bin/homegenie` after uninstalling the previous homegenie release (and before installing `stable.8`).

**Comment by soxfan1966** [comment]
How do you uninstall the previous homegenie release ?

**Comment by genemars** [comment]
`sudo dpkg --remove homegenie`

**Comment by soxfan1966** [comment]
OK - will try now.

**Comment by mralapete** [comment]
> I would disagree with you there mralapete - I think there is something amiss with the update process having to do with the stable 6 and stable 8 issue.

That's fine. I've pointed you in the right direction. The simplest method I suggested was to download https://github.com/genielabs/HomeGenie/releases/download/v1.3-stable.8/homegenie_1.3-stable.8.tgz to a local machine and do a manual upgrade via the HG GUI by pointing the upgrade to the locally downloaded release. This way even the yellow upgrade arrow But hey, I'll leave it to you.

**Comment by soxfan1966** [comment]
genemars - I went thru those steps and the same thing happened.  The dots appeared when the service was being started.   Interestingly, the service is running because I can connect again to HG.  I think I am running ver 1.3 stable 8, even though the yellow arrow is still appearing, but I can see the change to the options for Programs.

Any ideas on how to clean the rest of this up ?

**Comment by tuicemen** [comment]
I don't see the options in programs either ,However I'm wondering if this is a browser thing like the widget manager. Still see the yellow update icon as well.

**Comment by tuicemen** [comment]
Ok think I found it far right of the program there are 3 bars hovering over that the word options appears. Thought that was always there but guess not.

**Comment by soxfan1966** [comment]
via Putty on the Pi, I can stop and then start the homegenie.service with no problems.

I did this and then once on HomeGenie I ran the Update Check and now the yellow arrow and the notification of n update are both gone.

I am going to try and restore my settings backup now

**Comment by soxfan1966** [comment]
I have my backed up settings restored - the update notification is still appearing however.

**Comment by mralapete** [comment]
> I have my backed up settings restored - the update notification is still appearing however.

I’ve already mentioned how to get rid of the update arrow by simply doing a manual update. A manual update also ensures you have the update file already on your machine before you go through the install process. If you want to leave the yellow update icon in place so be it.

**Comment by soxfan1966** [comment]
I did a manual update.  I also deleted my prior version and installed the 1.3 stable 8 as Gene instructed.   And the update indicator is still showing.  I assume I am running version 8 at this point and there is some flag or file that needs to be cleared.
 Maybe it worked for you but it did not for me.

**Comment by mralapete** [comment]
> I did a manual update. I also deleted my prior version and installed the 1.3 stable 8 as Gene instructed. And the update indicator is still showing. I assume I am running version 8 at this point and there is some flag or file that needs to be cleared.
> Maybe it worked for you but it did not for me.

Just click on the option About from the drop down menu Configure. That will confirm what version you are using. You can still do the manual update I described earlier over version 8. That should remove the update arrow icon.

**Comment by mralapete** [comment]
I’ve also mentioned the old HG forum before as a wealth of information. Here you can see how all these update disasters can be remedied without all the fuss http://old.homegenie.club:8080/www.homegenie.it/forum/index3b74-2.html?topic=1362.0

**Comment by soxfan1966** [comment]
I am at ver 1.3 stable 8:
![image](https://user-images.githubusercontent.com/49078444/83696500-a0531e00-a5ca-11ea-8fe2-6ec81c114214.png)

I have already restored my setup twice today (including cleaning up all the extra stuff that gets added back when I update that I do not want or need) so I really have no intention of doing another manual update for the same release.  I will investigate the code and see if I can find where / why the update flag is being triggered.  Perhaps its something I can correct without having to try another manual update.

**Comment by mralapete** [comment]
You’ll probably need to run HG in debug mode, do an update and examine the update process in real time. Is it really worth it. That’s up to you to decide.

I sent you the method of doing a HG update from the CLI. Again a painless process. Once you’ve cleared the HG folder a simple wget of the latest release and tar it into the HG folder, you restore your HG settings backup and you’re good to go.

I’m done here so good luck with whatever choice you make. Life’s too short 😂

**Comment by soxfan1966** [comment]
"Once you’ve cleared the HG folder a simple wget of the latest release and tar it into the HG folder, you restore your HG settings backup and you’re good to go."

This is what Gene had me try earlier today - which I did.  It did not work.

Sorry,. but you keep coming off like your response is the one end all solution - even when I (or someone else) tells you it did not work.  We've gone back and forth - you suggest I try something, I say I already did and it didn't work, etc.   I appreciate the assistance, but honestly I could do without the holier than though tone.

**Comment by mralapete** [comment]
That’s fine. Wait till Gene comes back to you so. 

I’ve actually offered many alternatives not just one as has Gene and none seem to have worked for you. 

I’ve no idea what the “holier than thou” comment is about but if you want to spend hours at this that’s entirely up to you. Your time not mine.

**Comment by tuicemen** [comment]
I too have done a couple uninstalls removed the HomeGenie folder and even  installing version 7 prior to updating. For what ever reason  HG still sees a update (8) available. I guess it is something that may disappear when ver 9 is released if not I'll live with it.
